export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry"
];

export const MANPOWER_DESIGNATIONS = [
  { value: "Security Guard", label: "Security Guard" },
  { value: "Security Supervisor", label: "Security Supervisor" },
  { value: "Security Officer", label: "Security Officer" },
  { value: "Supervisor", label: "Supervisor" },
  { value: "Peon", label: "Peon" },
  { value: "Office Boy", label: "Office Boy" },
  { value: "Helper", label: "Helper" },
  { value: "Sweeper", label: "Sweeper" },
  { value: "Housekeeping Staff", label: "Housekeeping Staff" },
  { value: "Housekeeper", label: "Housekeeper" },
  { value: "Cleaner", label: "Cleaner" },
  { value: "Data Entry Operator", label: "Data Entry Operator" },
  { value: "DEO", label: "DEO" },
  { value: "MTS", label: "MTS" },
  { value: "Multi Tasking Staff", label: "Multi Tasking Staff" },
  { value: "Watchman", label: "Watchman" },
  { value: "Driver", label: "Driver" },
  { value: "Gardener", label: "Gardener" },
  { value: "Technician", label: "Technician" },
  { value: "Electrician", label: "Electrician" },
  { value: "Plumber", label: "Plumber" }
];
